builds:
- main: ./cmd/notify/main.go
  binary: notify
  env:
  - CGO_ENABLED=0
  ldflags:
    - -X github.com/montanaflynn/notify-cli.version=v{{.Version}}
    - -X github.com/montanaflynn/notify-cli.commit={{.Commit}}
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
